### ISSUE TITLE
rotating speaker view on website

### ISSUE THREAD

**Issue by csoneson** [Bioconductor/BioC2021#12]
Is it possible to have the 'Speakers' part of the main landing page automatically rotate through all the speakers (alternatively, show all the speakers on one page)? Right now, it's not immediately obvious that there are more than the four speakers shown on the first page.

**Comment by mdozmorov** [comment]
I couldn't solve it immediately. That's important, I [asked the developers](https://github.com/devcows/hugo-universal-theme/issues/288). A workaround would be to create a second row of panels. Let's see if we get help.

**Comment by mdozmorov** [comment]
No longer relevant as the current horizontal layout shows all speakers. Fixed in #15
