### ISSUE TITLE
Long workshop status

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/BioC2021#18]
This issue tracks the status of long workshops.

A passing badge is expected to reflect that the workshop:

- can be built as an R package
- can deploy pkgdown documentation to the `gh-pages` branch of the repository
- can push a Docker container to Docker Hub.

****

### Dimension Reduction for Beginners

[![R build status](https://github.com/aedin/PCAworkshop/actions/workflows/basic_checks.yaml/badge.svg)](https://github.com/aedin/PCAworkshop/actions)

### Epidemiology for Bioinformaticians

[![R build status](https://github.com/cmirzayi/EpiForBioWorkshop2021/actions/workflows/basic_checks.yaml/badge.svg)](https://github.com/cmirzayi/EpiForBioWorkshop2021/actions)

### Reproducing a single-cell proteomics data analysis using QFeatures and scp

[![R build status](https://github.com/lgatto/QFeaturesScpWorkshop2021/actions/workflows/basic_checks.yaml/badge.svg)](https://github.com/lgatto/QFeaturesScpWorkshop2021/actions)

### Introduction to the Terra/AnVIL Cloud-based Genomics Platform

[![R build status](https://github.com/waldronlab/AnVILWorkshop/actions/workflows/basic_checks.yaml/badge.svg)](https://github.com/waldronlab/AnVILWorkshop/actions)

### Building Carpentries-based Bioconductor Lessons

[![R build status](https://github.com/jdrnevich/BuildACarpentriesWorkshop/actions/workflows/basic_checks.yaml/badge.svg)](https://github.com/jdrnevich/BuildACarpentriesWorkshop/actions)

### Multi-omic Integration of cBioPortal and TCGA data with MultiAssayExperiment

[![R build status](https://github.com/waldronlab/MultiAssayWorkshop/workflows/MAEWorkshopCheck/badge.svg)](https://github.com/waldronlab/MultiAssayWorkshop/actions)

### Effectively using the DelayedArray framework to support the analysis of large datasets

[![R build status](https://github.com/PeteHaitch/BioC2020_DelayedArray_workshop/workflows/.github/workflows/basic_checks.yaml/badge.svg)](https://github.com/PeteHaitch/BioC2020_DelayedArray_workshop/actions)

### Introduction to Bioconductor annotation resources

[![R build status](https://github.com/jmacdon/Bioc2021Anno/workflows/.github/workflows/basic_checks.yaml/badge.svg)](https://github.com/jmacdon/Bioc2021Anno/actions)

### Trajectory inference across conditions: differential expression and differential progression

[![R build status](https://github.com/kstreet13/bioc2020trajectories/workflows/.github/workflows/basic_checks.yaml/badge.svg)](https://github.com/kstreet13/bioc2020trajectories/actions)

### systemPipe: Workflow and Visualization Toolkit

[![R build status](https://github.com/systemPipeR/systemPipeWorkshop2021/workflows/.github/workflows/basic_checks.yaml/badge.svg)](https://github.com/systemPipeR/systemPipeWorkshop2021/actions)

### Interfacing Bioconductor with tidyverse with tidySingleCellExperiment and tidySummarisedExperiment

[![R build status](https://github.com/stemangiola/bioc2021_tidytranscriptomics/workflows/.github/workflows/basic_checks.yaml/badge.svg)](https://github.com/stemangiola/bioc2021_tidytranscriptomics/actions)

**Comment by jdrnevich** [comment]
Hi @kevinrue . I see our Building Carpentries-based Bioconductor Lessons is failing. Is there any information on what is failing?

**Comment by kevinrue** [comment]
Latest CI run report here: https://github.com/jdrnevich/BuildACarpentriesWorkshop/runs/2124169713?check_suite_focus=true

I suggest we open an issue on the workshop repository instead. Otherwise this one would rapidly get overcrowded.

**Comment by kevinrue** [comment]
Uh oh. It seems that cloning Sean's repo has undesirable side effects, as in it is not possible to open issues on the repository. 
We need to update the instructions to say that people should use the "Use as template" button instead.

**Comment by jdrnevich** [comment]
Yeah, I figured that out the hard way. I'm not seeing certain other things either. I wonder if I should scrap it and start again?

**Comment by kevinrue** [comment]
To me, it would feel cleaner to restart it using as template, yes. Changing settings on the current setup may not guarantee that the result is the same as using as template, which worked when I tested.

**Comment by lwaldron** [comment]
Yes, I think you have to start again by deleting your forked repository and re-creating a new one under the same name, or creating the new one under a different name then re-naming it to the name of your former forked repo. You could start by creating from template but you don't have to, if you want to keep your commit history you could import your local local git project to github:
https://docs.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github/importing-a-git-repository-using-the-command-line

**Comment by jdrnevich** [comment]
I don't care that much about the commit history. I did clone the template properly to https://github.com/jdrnevich/testWorkshop doing the minimal changes necessary, although it's still failing at the Docker step (hoping I just input my DOCKER_PASSWORD wrong). Once I get that to work, I'll copy over the few pages I had customized from the previous one, then delete the old one and re-name the new one.

**Comment by mdozmorov** [comment]
@kevinrue, what do you think about creating a workshop page on the website, like we had last year https://bioc2020.bioconductor.org/workshops, and moving those status badges there?

**Comment by kevinrue** [comment]
Sure! About to have dinner now, but I can look at that later.

**Comment by mdozmorov** [comment]
Last year, Marcel @LiNk-NY created a nice code that compiles the workshop page in markdown, https://github.com/Bioconductor/BioC2020/blob/master/docs/workshops.Rmd. Should be straightforward to adapt for this year.

**Comment by kevinrue** [comment]
Would you mind giving me write access to the repository? Otherwise I can make a fork, if you prefer.

**Comment by mdozmorov** [comment]
Should be done. Please, let me know if I can help.

**Comment by kevinrue** [comment]
For some reason it still doesn't work

```
git push -u origin workshops
```

No problem. I'll make a fork.

Also it's still a work in progress. We can have some rounds of feedback about the layout. I'm not sure you'd want the CI badges on the conference website, which is why I created this issue in the first place.

**Comment by mdozmorov** [comment]
It still shows "Awaiting response." Did you receive an e-mail to click through the invite? 

And yes, badges on the website, an additional column. It may take creating shortcodes.

**Comment by kevinrue** [comment]
Ah right - I didn't see the invitation email. Those tend to fly under the radar, unlike github action build reports.

**Comment by kevinrue** [comment]
I guess we can close this issue, now that the badges are on the main website.
(Even closed, this issue will keep showing the badges anyway, actually)

**Comment by mdozmorov** [comment]
Yes, the status page https://bioc2021.bioconductor.org/workshops-status/ looks great. Thanks so much, @kevinrue!
