### ISSUE TITLE
Add the dates of the conference

### ISSUE THREAD

**Issue by csoneson** [Bioconductor/BioC2021#9]
- [ ] The `schedule` page still has the dates from last year
- [ ] Also add dates to the landing page

**Comment by mdozmorov** [comment]
For the schedule, the partial table is commented out. 

Dates are actually there, along with the call for submission.

**Comment by csoneson** [comment]
Only the dates for the submission were there - the dates of the conference are not provided anywhere I think. I added them to the submission page in https://github.com/Bioconductor/BioC2021/pull/10, but they should be made more prominent in other places too.

**Comment by mdozmorov** [comment]
Sorry, misunderstood. Will add the conference dates to the landing page shortly.
